"""removed API_KEY column

Revision ID: 2952711e134f
Revises: 473b09c008f2
Create Date: 2022-05-03 18:15:05.314219
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2952711e134f'
down_revision = '473b09c008f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'api_key',
            sa.VARCHAR(length=511),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
